# route:
#   receiver: 'logstash'
#   repeat_interval: 3h #3h
#   group_interval: 5m #5m
#   group_wait: 1m #1m
#   routes:
#   - receiver: 'logstash'
#     continue: true
#   # - receiver: 'slack'




# receivers:
#     # - name: 'slack'
#     #   slack_configs:
#     #     - send_resolved: true
#     #       username: 'Prometheus - Alerts'
#     #       channel: '#channel'
#     #       api_url: # Put your slack webhook_url here.
#     #       text: '{{ .CommonAnnotations.summary }}   --->   {{ .CommonAnnotations.description }}'
#     - name: 'logstash'
#       webhook_configs:
#         # Whether or not to notify about resolved alerts.
#         - send_resolved: true
#           # The endpoint to send HTTP POST requests to.
#           url: "http://logstash:8080/"

route:
  receiver: 'email'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  #group_by: [cluster, alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  # All alerts with service=mysql or service=cassandra
  # are dispatched to the database pager.
  - receiver: 'email'


receivers:
  - name: 'email'
    email_configs:
      - to: test@test.com
        from: test@test.com
        smarthost: smtp.test.com:587
        auth_username: "$EMAIL_ACCOUNT"
        auth_password: "$EMAIL_AUTH_TOKEN"
      